#!/usr/bin/env node
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { writeFileSync, rmSync, existsSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createComToolRunner } from '../../extendscript-toolchain/src/comtool-compat.mjs';

var ROOT = dirname(fileURLToPath(import.meta.url));
var PROJECT = dirname(ROOT);
var COM = createComToolRunner();
var probePath = join(ROOT, '.eshash-live-verify-' + process.pid + '-' + Date.now() + '.jsx');

function utf16Hex(text) {
  var out = '';
  var i;
  var unit;
  var hex;
  for (i = 0; i < text.length; i++) {
    unit = text.charCodeAt(i).toString(16);
    while (unit.length < 4) unit = '0' + unit;
    out += unit;
  }
  return out;
}

function referenceCrc(buffer) {
  var crc = 0xFFFFFFFF;
  var i;
  var bit;
  var shifted;
  for (i = 0; i < buffer.length; i++) {
    crc = crc ^ buffer[i];
    for (bit = 0; bit < 8; bit++) {
      if ((crc & 1) !== 0) {
        shifted = crc >>> 1;
        crc = shifted ^ 0xEDB88320;
      } else {
        crc = crc >>> 1;
      }
    }
  }
  var inverted = crc ^ 0xFFFFFFFF;
  return inverted >>> 0;
}

var vectors = [];
function addBytes(label, value) {
  var buffer = Buffer.from(value, 'latin1');
  vectors.push({
    label: label,
    kind: 'bytes',
    parts: [utf16Hex(value)],
    sha256: createHash('sha256').update(buffer).digest('hex'),
    crc32: referenceCrc(buffer)
  });
}
function addText(label, value) {
  var buffer = Buffer.from(value, 'utf8');
  vectors.push({
    label: label,
    kind: 'text',
    parts: [utf16Hex(value)],
    sha256: createHash('sha256').update(buffer).digest('hex'),
    crc32: referenceCrc(buffer)
  });
}

addBytes('empty bytes', '');
addBytes('FIPS abc bytes', 'abc');
addBytes('CRC check bytes', '123456789');
var allBytes = '';
for (var i = 0; i < 256; i++) allBytes += String.fromCharCode(i);
addBytes('all byte values 0..255', allBytes);

var edgeLengths = [55, 56, 57, 63, 64, 119, 120];
for (i = 0; i < edgeLengths.length; i++) {
  var edge = '';
  for (var j = 0; j < edgeLengths[i]; j++) edge += String.fromCharCode((j * 37 + edgeLengths[i]) & 0xFF);
  addBytes('padding boundary ' + edgeLengths[i], edge);
}

addText('UTF-8 NUL and Latin-1', '\u0000\u007f\u0080\u00e9');
addText('UTF-8 supplementary scalar', 'prefix\ud83d\ude00suffix');
addText('UTF-8 lone high surrogate replacement', 'left\ud800right');
addText('UTF-8 lone low surrogate replacement', 'left\udfff\u0000right');
addText('UTF-8 split-sensitive boundary text', 'A'.repeat(55) + '\ud83d\ude00' + '\u00e9');

var streamText = 'left\ud83d\ude00right\ud800end';
var streamTextBuffer = Buffer.from(streamText, 'utf8');
vectors.push({
  label: 'text stream splits surrogate pair',
  kind: 'streamText',
  parts: [utf16Hex('left\ud83d'), utf16Hex('\ude00right\ud800'), utf16Hex('end')],
  sha256: createHash('sha256').update(streamTextBuffer).digest('hex'),
  crc32: referenceCrc(streamTextBuffer)
});
var streamBytes = allBytes + 'tail';
var streamBytesBuffer = Buffer.from(streamBytes, 'latin1');
vectors.push({
  label: 'binary stream split around block boundary',
  kind: 'streamBytes',
  parts: [utf16Hex(streamBytes.substring(0, 63)), utf16Hex(streamBytes.substring(63, 65)), utf16Hex(streamBytes.substring(65))],
  sha256: createHash('sha256').update(streamBytesBuffer).digest('hex'),
  crc32: referenceCrc(streamBytesBuffer)
});

var jsxPath = join(PROJECT, 'dist', 'ESHASH.jsx').replace(/\\/g, '/');
var nativeManifest = join(PROJECT, 'dist', 'native', 'ESHASHNative.current');
var nativePath = process.env.ESHASH_NATIVE_DLL ||
  (existsSync(nativeManifest)
    ? join(PROJECT, 'dist', 'native', readFileSync(nativeManifest, 'utf8'))
    : '');
nativePath = nativePath.replace(/\\/g, '/');
var probe = [
  '#target illustrator',
  '// generated by tests/live-verify.mjs; safe hex transport for NUL and surrogates',
  '$.evalFile(File(' + JSON.stringify(jsxPath) + '));',
  'var eshashApi = $.global["ESHASH"];',
  'var eshashVectors = ' + JSON.stringify(vectors) + ';',
  'function eshashFromHex(hex) {',
  '  var out = "", i, value;',
  '  for (i = 0; i < hex.length; i += 4) { value = parseInt(hex.substring(i, i + 4), 16); out += String.fromCharCode(value); }',
  '  return out;',
  '}',
  'var eshashFallbackPassed = eshashApi.sha256Bytes("abc") === "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" && eshashApi.crc32Bytes("123456789") === 0xCBF43926;',
  'if (!eshashFallbackPassed) throw new Error("pure-JSX fallback preflight failed");',
  'var eshashNativeLoaded = ' + (nativePath && existsSync(nativePath) ? 'eshashApi.loadNative(' + JSON.stringify(nativePath) + ')' : 'false') + ';',
  'var eshashFailures = [];',
  'var eshashIndex, eshashPart, eshashValue, eshashSha, eshashCrc, eshashPiece;',
  'for (eshashIndex = 0; eshashIndex < eshashVectors.length; eshashIndex++) {',
  '  var eshashVector = eshashVectors[eshashIndex];',
  '  eshashSha = eshashApi.createSha256();',
  '  eshashCrc = eshashApi.createCrc32();',
  '  for (eshashPart = 0; eshashPart < eshashVector.parts.length; eshashPart++) {',
  '    eshashPiece = eshashFromHex(eshashVector.parts[eshashPart]);',
  '    if (eshashVector.kind === "bytes" || eshashVector.kind === "streamBytes") {',
  '      eshashSha.updateBytes(eshashPiece); eshashCrc.updateBytes(eshashPiece);',
  '    } else { eshashSha.updateText(eshashPiece); eshashCrc.updateText(eshashPiece); }',
  '  }',
  '  var gotSha = eshashSha.digest();',
  '  var gotCrc = eshashCrc.digest();',
  '  if (gotSha !== eshashVector.sha256) { eshashFailures[eshashFailures.length] = eshashVector.label + " SHA expected " + eshashVector.sha256 + " got " + gotSha; }',
  '  if (gotCrc !== eshashVector.crc32) { eshashFailures[eshashFailures.length] = eshashVector.label + " CRC expected " + eshashVector.crc32 + " got " + gotCrc; }',
  '  if (eshashVector.kind === "bytes" || eshashVector.kind === "text") {',
  '    eshashValue = eshashVector.kind === "bytes" ? eshashApi.sha256Bytes(eshashFromHex(eshashVector.parts[0])) : eshashApi.sha256Text(eshashFromHex(eshashVector.parts[0]));',
  '    if (eshashValue !== eshashVector.sha256) { eshashFailures[eshashFailures.length] = eshashVector.label + " one-shot SHA mismatch"; }',
  '    eshashValue = eshashVector.kind === "bytes" ? eshashApi.crc32Bytes(eshashFromHex(eshashVector.parts[0])) : eshashApi.crc32Text(eshashFromHex(eshashVector.parts[0]));',
  '    if (eshashValue !== eshashVector.crc32) { eshashFailures[eshashFailures.length] = eshashVector.label + " one-shot CRC mismatch"; }',
  '  }',
  '  if (eshashNativeLoaded && (eshashVector.kind === "bytes" || eshashVector.kind === "streamBytes")) {',
  '    var nativeBytes = "", nativePartIndex;',
  '    for (nativePartIndex = 0; nativePartIndex < eshashVector.parts.length; nativePartIndex++) { nativeBytes += eshashFromHex(eshashVector.parts[nativePartIndex]); }',
  '    if (eshashApi.sha256Bytes(nativeBytes) !== eshashVector.sha256) eshashFailures[eshashFailures.length] = eshashVector.label + " native SHA mismatch";',
  '    if (eshashApi.crc32Bytes(nativeBytes) !== eshashVector.crc32) eshashFailures[eshashFailures.length] = eshashVector.label + " native CRC mismatch";',
  '  }',
  '}',
  'var eshashNativeStatus = eshashApi.nativeStatus();',
  'if (eshashNativeLoaded) eshashApi.unloadNative();',
  '({ ok: eshashFailures.length === 0, total: eshashVectors.length, failures: eshashFailures, engine: $.version, facade: typeof eshashApi, sha256: typeof eshashApi.sha256Bytes, crc32: typeof eshashApi.crc32Bytes, nativeLoaded: eshashNativeLoaded, nativeStatus: eshashNativeStatus });'
].join('\n');

try {
  writeFileSync(probePath, probe, 'utf8');
  console.log('[live-verify] running ' + vectors.length + ' vectors in already-running Illustrator through COMTool V2 (no launch)');
  var text = await COM.runText(['eval', '--file', probePath], { timeoutMs: 120000 });
  var envelope = JSON.parse(text);
  if (!envelope.ok) {
    throw new Error(JSON.stringify(envelope.error || envelope));
  }
  var report = envelope.result && envelope.result.result ? envelope.result.result : envelope.result;
  assert.equal(report.ok, true, JSON.stringify(report.failures));
  assert.equal(report.total, vectors.length);
  if (report.nativeLoaded) assert.equal(report.nativeStatus.abiRevision, 1, 'native ESABI revision');
  console.log('[live-verify] ' + report.total + ' vectors passed on ExtendScript ' + report.engine + '; facade/functions present; native=' + report.nativeLoaded + (report.nativeLoaded ? ' (file transport parity)' : ' (JSX fallback only)'));
} catch (error) {
  console.error('[live-verify] failed: ' + String(error && error.message ? error.message : error));
  process.exitCode = 1;
} finally {
  rmSync(probePath, { force: true });
  await COM.close().catch(function () {});
}
